export const STORE_PERSONAL_DETAILS = 'STORE_PERSONAL_DETAILS';
export const PERSONAL_DETAILS_NEXT = 'PERSONAL_DETAILS_NEXT';

export const STORE_PROFESSIONAL_DETAILS = 'STORE_PROFESSIONAL_DETAILS';
export const PROFESSIONAL_DETAILS_NEXT = 'PROFESSIONAL_DETAILS_NEXT';

export const SUBMIT_ALL_DETAILS = 'SUBMIT_ALL_DETAILS';